version: '3.7'

services:
  ecom:
    restart: always
    expose: 
      - "8000"
    ports:
      - "8000:8000"
    build:
      context: .
    depends_on:
      - db
    volumes:
      - static_data:/vol/web
    environment: 
      - SECRET_KEY=tjp!u#8t0f21!@yt8^pk@vtk3de0eh56*_1=o(x64o8_u&t2$$8
      - ALLOWED_HOSTS=127.0.0.1, localhost, 0.0.0.0
  
  proxy:
    restart: always
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - ecom
  
  db:
    restart: always
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "ecom"
      MYSQL_USER: root
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_HOST: 'localhost'
      MYSQL_ROOT_PASSWORD: "root"

volumes:
  static_data: 