version: '3.7'

services:
  ecom:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn ecom.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./ecom:/ecom
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=0
