version: '3.7'

services:
  ecom:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY='tjp!u#8t0f21!@yt8^pk@vtk3de0eh56*_1=o(x64o8_u&t2$$8'
      - ALLOWED_HOSTS=127.0.0.1,localhost
      - ALLOWED_HOSTS=http://127.0.0.1, localhost
      - DJANGO_CORS_ORIGIN_WHITELIST=http://127.0.0.1, localhost
      - API_URL=http://127.0.0.1, localhost
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - ecom

volumes:
  static_data: